os: linux
language: r
dist: xenial
latex: false

branches:
  only:
    - main

cache:
  packages: yes
  directories:
    - $HOME/bin

install:
  - Rscript -e 'source("R/install.R")'

script:
  - Rscript -e 'source("R/script.R")'

deploy:
  provider: pages
  strategy: git
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  on:
    branch: main
  local-dir: public
  # fqdn: nikitagusarov.github.io
  repo: nikitagusarov/nikitagusarov.github.io
  target_branch: main
