title: Welcome!
baseURL: https://nikitagusarov.github.io/
languageCode: en-us
theme: gohugo-theme-ananke
resourceDir: resources
publishDir: public
DefaultContentLanguage: en
# SectionPagesMenu: main
Paginate: 9
googleAnalytics: ''
enableRobotsTXT: yes
languages:
  en:
    contentDir: content/en
    title: Nikita Gusarov
    weight: 1
    menu:
      main:
        - name: About
          url: /about
          weight: 0
        - name: Background
          url: /background
          weight: 1
        - name: Contact
          url: /contact
          weight: 3
        - name: Activities
          weight: 4
        # - name: Development
        #   url: /development
        #   weight: 0
        # - name: Publications
        #   url: /publications
        #   weight: 0
        # - name: Talks
        #   url: /talks
        #   weight: 0
sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5
params:
  featured_image: images/default_x220.png
  body_classes: "courrier bg-near-white"
  post_content_classes: "courrier bg-near-white"
  background_color_class: bg-black
  recent_posts_number: 6
  # custom_css: [custom.css]
  # omit_header_text: true
  description: 
  github: 'https://github.com/nikitagusarov'
  gitlab: 'https://gitlab.com/nikitagusarov'
  linkedin: 'https://linkedin.com/in/nikitagusarov'
  # instagram: ''
  # facebook: ''
  # favicon: ''
  # mastodon: ''
  # rss: ''
  # site_logo: '/images/id_git.png'
  # slack: ''
  # stackoverflow: ''
  # twitter: ''
  # youtube: ''
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
markup:
  goldmark:
    renderer:
      unsafe: true
selfcontained: true
