title: Welcome!
baseURL: https://nikitagusarov.github.io/
languageCode: en-us
theme: gohugo-theme-ananke
resourceDir: resources
publishDir: public
DefaultContentLanguage: en
SectionPagesMenu: main
Paginate: 3
googleAnalytics: ''
enableRobotsTXT: yes
languages:
  en:
    contentDir: content/en
    title: Nikita Gusarov
    weight: 1
sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5
params:
  featured_image: images/default_x220.png
  body_classes: "courrier bg-near-white"
  post_content_classes: "courrier bg-near-white"
  # custom_css: [custom.css]
  # omit_header_text: true
  background_color_class: bg-black
  description: 
  # facebook: ''
  # favicon: ''
  github: 'https://github.com/nikitagusarov'
  gitlab: 'https://gitlab.com/nikitagusarov'
  # instagram: ''
  linkedin: 'https://www.linkedin.com/in/nikita-gusarov-264a25175'
  # mastodon: ''
  recent_posts_number: 5
  # rss: ''
  # site_logo: '/images/id_git.png'
  # slack: ''
  # stackoverflow: ''
  # twitter: https://twitter.com/GoHugoIO
  # youtube: ''
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
markup:
  goldmark:
    renderer:
      unsafe: true
selfcontained: true
